import {help,installHelp} from './explain.js';
import {installDetails,showDay} from './details.js';
import {stats, correlation, rolling, escapeHtml as esc} from './math.js';
const $=s=>document.querySelector(s);
const COLORS=['#3d75ef','#36b3a2','#e9ac4e','#a385df','#ed8998','#6bb4cd','#5968b2','#a6b3c6'];
const OS=['os_1','os_2','os_3','os_4','os_5','os_6','os_7','被动'];
const NAMES=['衣装','鞋履箱包','茶点饮品','珠宝配饰','材料矿石','玩偶','花卉美妆','专属 OSA'];
const ICONS=['👕','👟','🍰','💎','🧵','🧸','🌷','🎁'];
const PATHS={overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',rhythm:'M3 17l5-9 5 6 8-12M3 21h18',generators:'M12 3l9 5v8l-9 5-9-5V8zM3 8l9 5 9-5M12 13v8',board:'M3 3h18v18H3zM3 9h18M3 15h18M9 3v18M15 3v18',catalog:'M4 3h6v18H4zM14 3h6v18h-6z',source:'M3 5h18v14H3zM3 10h18M9 5v14'};
const PAGES=[['overview','体验总览'],['rhythm','订单节奏'],['generators','物品产出'],['board','机器人游乐场'],['catalog','物品图鉴'],['source','数据与说明']];
const chartSeriesStorage='merge-lab-chart-series-v1';
const chartSeries={actual:true,trend:true,target:true};
try{const saved=JSON.parse(localStorage.getItem(chartSeriesStorage)||'null');for(const key of Object.keys(chartSeries))if(typeof saved?.[key]==='boolean')chartSeries[key]=saved[key]}catch{}
let D,state={page:'overview',store:16,day:326,from:326,to:350,metric:'stamina',mode:'bars',os:'os_3',search:'',catalogPage:1};
let byName,byRow,byDay;
const fmt=(n,dec=0)=>Number.isFinite(n)?n.toLocaleString('zh-CN',{maximumFractionDigits:dec}):'—';
const pct=(n,dec=1)=>Number.isFinite(n)?`${(n*100).toFixed(dec)}%`:'—';
const icon=(key)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${PATHS[key]}"/></svg>`;
const osLabel=k=>k==='被动'?'OSA':k.replace('_','').toUpperCase();
const numConfig=(key,fallback=0)=>Number(D.config[key]??fallback);
const ds=()=>D.days.filter(d=>(state.store===0||d.store===state.store)&&d.day>=state.from&&d.day<=state.to);
const validDays=()=>ds().filter(d=>d.complete);
const ordersFor=day=>(byDay.get(Number(day))?.orders??[]).map(r=>byRow.get(r));
function glyph(item){let chain=item?.chain??Object.keys(item?.needs??{})[0]??'';return ICONS[chain.includes('_a_')?7:Math.max(0,Number(chain.split('_')[1])-1)]??'📦'}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function render(){
 const title=PAGES.find(p=>p[0]===state.page)?.[1];
 $('#app').innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brandmark">M</span><div><strong>MERGE LAB</strong><small>游戏数值实验室</small></div></div><div class="nav-label">WORKSPACE</div><nav aria-label="主导航">${PAGES.map(([id,name])=>`<button class="nav-item ${state.page===id?'active':''}" data-page="${id}" ${state.page===id?'aria-current="page"':''}>${icon(id)}${name}${id==='board'?'<span class="tiny-tag">PLAY</span>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="sidebar-note"><strong>真实配置 · 自由探索</strong>${D.meta.sheets.length} 张工作表 / ${fmt(D.items.length)} 个物品<br>7 × 8 棋盘实验</div><strong>MERGE GAME</strong>数据快照 ${new Date(D.meta.sourceModifiedAt).toLocaleDateString('zh-CN')}<br>数值逻辑.xlsx</div></aside><div class="workspace"><header class="topbar"><div class="breadcrumb">工作空间 <span>/</span> <b>${title}</b></div><div class="top-tools"><span class="status-badge">配置已载入</span><button class="small ghost" data-page="source">数据与说明</button><span class="avatar">MG</span></div></header><main class="main" id="main"><div class="page-heading"><div><div class="eyebrow">${state.page==='board'?'PLAY & EXPERIMENT':'BALANCE & PACING'}</div><h1>${title}</h1><p class="subtitle">${pageSubtitle()}</p></div><div class="heading-actions"><button class="ghost" id="export-csv">↓ 导出数据</button><button class="primary" data-page="board">🤖 看机器人玩</button></div></div>${toolbar()}<div id="content" class="fade-in"></div><footer class="page-footer"><span>MERGE LAB / 配置驱动的数值探索</span><span>当前店铺已复算 · ${fmt(D.orders.length)} 张订单 · ${D.days.length} 天 · ${new Set(D.days.map(d=>d.store)).size} 家店铺</span></footer></main></div></div>`;
 renderContent();bindShell();
}
function pageSubtitle(){return {overview:'从整店负载，到每一次合成。让配置里的节奏看得见。',rhythm:'沿着时间轴，拆解每一天、每一单的压力与释放。',generators:'观察七条生成器的参与、错峰与库存积累。',board:'把真实订单搬上棋盘，体验生成、合成、加工与交付。',catalog:'查找物品，追溯配方，看到每条产出链的需求。',source:'查看原始表格、配置参数与计算边界。'}[state.page]}
function toolbar(){let stores=[...new Set(D.days.map(d=>d.store))];return `<div class="toolbar"><label>店铺 <select id="store-select" aria-label="选择店铺"><option value="0" ${state.store===0?'selected':''}>全部店铺</option>${stores.map(n=>`<option value="${n}" ${state.store===n?'selected':''}>店铺 ${String(n).padStart(2,'0')}</option>`).join('')}</select></label><span class="divider"></span><label>DAY <input id="from-day" type="number" min="1" max="350" value="${state.from}" aria-label="开始day"> — <input id="to-day" type="number" min="1" max="350" value="${state.to}" aria-label="结束day"></label><button class="small" id="apply-range">应用</button><button class="small ghost" id="reset-range">全店范围</button><span class="spacer"></span><span class="muted" style="font-size:.75rem">${ds().length} 天 · ${fmt(ds().reduce((n,d)=>n+d.orders.length,0))} 张订单</span></div>`}
function bindShell(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$('#store-select').onchange=e=>{state.store=+e.target.value;resetRange();render()};$('#apply-range').onclick=()=>{let a=+$('#from-day').value,b=+$('#to-day').value;if(a>b||!D.days.some(d=>d.day>=a&&d.day<=b&&(state.store===0||d.store===state.store))){toast('请选择有数据的日期范围');return}state.from=a;state.to=b;state.day=ds()[0].day;render()};$('#reset-range').onclick=()=>{resetRange();render()};$('#export-csv').onclick=exportCSV}
function navigate(page){state.page=page;if(page!=='board')stopBoard?.();render()}
function resetRange(){let a=D.days.filter(d=>state.store===0||d.store===state.store);state.from=a[0].day;state.to=a.at(-1).day;state.day=a[0].day}

function dataNotice(){let a=ds(),fresh=a.filter(d=>d.recalculated).length;return `<div class="data-note"><span>ⓘ ${fresh===a.length?'当前店铺已复算':fresh?`${fresh}天已复算，其余为历史数据`:'历史数据快照'}</span><span class="data-note-detail">详细说明见数据与说明</span></div>`}

function metrics(){let a=validDays(),s=stats(a.map(d=>d.stamina)),orders=a.reduce((n,d)=>n+d.orders.length,0);return `<div class="metric-grid">${metric('订单总数',fmt(orders),'单',`${a.length} 天`,'📦')}${metric('需要多少体力',fmt(s.sum),'',`每天约 ${fmt(s.mean)} 体力`,'⚡')}${metric('体力最高一天',fmt(s.max),'体力','点击查看这一天的订单','↗')}${metric('平均每单',fmt(s.sum/orders,1),'体力','按当前范围计算','◷')}</div>`}
function metric(label,value,unit,foot,symbol){const keys={'订单总数':'orderCount','需要多少体力':'totalEnergy','体力最高一天':'peakEnergy','平均每单':'orderMean','平均 / 峰值':'osMeanPeak','最少的一天':'minClicks','生成次数占比':'share','原始工作表':'sheets','物品 / 配方':'itemsRecipes','物品需求待核对':'itemProblems','订单需求待核对':'orderProblems','一级等价物品':'units','额外点击':'extraClicks'},key=keys[label]??'osClicks',dateKeys=['orderCount','totalEnergy','peakEnergy','orderMean'],osKeys=['osClicks','osMeanPeak','minClicks','share'],link=dateKeys.includes(key)?`data-metric-detail="${key==='peakEnergy'?'peak':'range'}"`:osKeys.includes(key)?`data-os-detail="${state.os}"`:`data-help="${key}" data-help-title="${esc(label)}"`;return `<article class="metric"><div class="metric-top">${label}${help(key,label)}<span class="metric-symbol">${symbol}</span></div><div class="metric-value num" ${link} role="button" tabindex="0">${value}${unit?`<small>${unit}</small>`:''}</div><div class="metric-foot">${foot}</div></article>`}
function valueFor(d){return state.metric==='stamina'?d.stamina:(d.clicks[state.metric]??0)}
function chart(){
  const a=ds(),W=1000,H=252,L=52,R=14,T=16,B=34,cw=W-L-R,ch=H-T-B;
  const vals=a.map(valueFor),ma=rolling(vals,3),showActual=chartSeries.actual,showTrend=chartSeries.trend,showTarget=state.metric==='stamina'&&chartSeries.target;
  if(!showActual&&!showTrend&&!showTarget)return '<div class="chart-empty" role="status">勾选上方项目，选择要显示的数据</div>';
  const visible=[...(showActual?vals:[]),...(showTrend?ma:[]),...(showTarget?a.map(d=>d.target):[])].filter(Number.isFinite);
  const max=Math.max(1,...visible)*1.1,step=cw/Math.max(1,a.length),x=i=>L+(i+.5)*step,y=v=>T+ch-v/max*ch;
  const tooltip=(d,i)=>[`第${d.day}天`,...(showActual?[`${state.metric==='stamina'?'体力':'点击'} ${fmt(vals[i],2)}`]:[]),...(showTrend?[`近期趋势 ${fmt(ma[i],2)}`]:[]),...(showTarget?[`计划体力 ${fmt(d.target)}`]:[])].join(' · ');
  return `<div class="chart-wrap"><svg class="chart-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="每日${state.metric==='stamina'?'体力':osLabel(state.metric)+'点击'}图，可点击查看当天订单">
    <defs><linearGradient id="bar-grad" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#4b80f3"/><stop offset="1" stop-color="#9abbff"/></linearGradient></defs>
    ${[0,1,2,3,4].map(n=>`<line x1="${L}" x2="${W-R}" y1="${y(max*n/4)}" y2="${y(max*n/4)}" stroke="#eaf0f7" stroke-dasharray="3 5"/><text x="${L-12}" y="${y(max*n/4)+4}" text-anchor="end">${fmt(max*n/4)}</text>`).join('')}
    ${showActual?`<g data-chart-layer="actual">${state.mode==='bars'?a.map((d,i)=>`<rect class="bar" x="${x(i)-step*.31}" y="${y(vals[i])}" width="${Math.max(1,step*.62)}" height="${ch-(y(vals[i])-T)}" rx="${Math.min(4,step*.15)}" fill="${!d.complete?'#c4ccd8':d.day===state.day?'#3168ed':'url(#bar-grad)'}"/>`).join(''):`<polyline points="${vals.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" fill="none" stroke="#3d75ef" stroke-width="2.8"/>${a.map((d,i)=>`<circle cx="${x(i)}" cy="${y(vals[i])}" r="3" fill="#3d75ef"/>`).join('')}`}</g>`:''}
    ${showTarget?`<polyline data-chart-layer="target" points="${a.map((d,i)=>d.target==null?'':`${x(i)},${y(d.target)}`).join(' ')}" fill="none" stroke="#f0b35c" stroke-width="1.7" stroke-dasharray="4 4"/>`:''}
    ${showTrend?`<polyline data-chart-layer="trend" points="${ma.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" fill="none" stroke="#1cac9c" stroke-width="2.5"/>`:''}
    ${a.map((d,i)=>`<g class="day-hit" data-day="${d.day}" tabindex="0" role="button" aria-label="查看第${d.day}天订单"><rect x="${L+i*step}" y="${T}" width="${step}" height="${ch}" fill="transparent"/><title>${tooltip(d,i)}</title></g>`).join('')}
    ${a.map((d,i)=>i%Math.max(1,Math.ceil(a.length/14))===0||i===a.length-1?`<text x="${x(i)}" y="${H-9}" text-anchor="middle">${d.day}</text>`:'').join('')}
  </svg></div>`;
}
function chartPanel(){
  const series=[['actual',state.metric==='stamina'?'体力':osLabel(state.metric)+'点击','#6b99f8',state.metric==='stamina'?'modelEnergy':'dailyClicks'],['trend','近期趋势','#1cac9c','recentTrend'],...(state.metric==='stamina'?[['target','计划体力','#f0b35c','dailyTarget']]:[])];
  return `<section class="panel"><div class="panel-head"><div><h2>${state.metric==='stamina'?'每天体力':'每天生成多少次'} ${help(state.metric==='stamina'?'energyChart':'clickChart')}</h2><p>点击图表查看当天订单</p></div><div class="segment"><button class="${state.mode==='bars'?'active':''}" data-mode="bars">柱形</button><button class="${state.mode==='line'?'active':''}" data-mode="line">趋势</button></div></div><div class="panel-body"><div class="split chart-controls"><div class="chart-series-controls" role="group" aria-label="显示内容"><span class="chart-series-label">显示</span>${series.map(([key,label,color,explanation])=>`<div class="series-control ${chartSeries[key]?'':'off'}" style="--series-color:${color}"><label><input type="checkbox" data-chart-series="${key}" ${chartSeries[key]?'checked':''}><i aria-hidden="true"></i><span>${label}</span></label>${help(explanation,label)}</div>`).join('')}</div><select id="metric-select" aria-label="图表指标"><option value="stamina">全部体力</option>${OS.map(k=>`<option value="${k}" ${state.metric===k?'selected':''}>${osLabel(k)} 点击</option>`).join('')}</select></div>${chart()}</div><div class="chart-footer"><span>DAY ${state.from}—${state.to} <span style="margin:0 10px">/</span> ${ds().length} 天</span><span>${state.metric==='stamina'?'体力':'点击'}峰值 <strong>${fmt(Math.max(...validDays().map(valueFor),0),1)}</strong> <span style="margin:0 9px">·</span> 点击图表查看订单</span></div></section>`;
}
function heatmap(){let a=ds();return `<div class="scroll-x"><div class="heatmap" style="--cols:${a.length};min-width:${Math.max(500,a.length*20+52)}px">${OS.slice(0,7).map((k,j)=>{let max=Math.max(1,...a.map(d=>d.clicks[k]||0));return `<div class="heatrow"><span class="heat-label">${ICONS[j]} ${osLabel(k)}</span>${a.map(d=>`<button class="heat" data-day="${d.day}" data-day-os="${k}" aria-label="Day ${d.day} ${osLabel(k)} ${fmt(d.clicks[k],1)}点击" title="Day ${d.day} · ${osLabel(k)} ${fmt(d.clicks[k],1)}" style="background:color-mix(in srgb,${COLORS[j]} ${12+(d.clicks[k]||0)/max*83}%,white)"></button>`).join('')}</div>`}).join('')}<div class="heatrow days"><span></span>${a.map((d,i)=>`<button data-day="${d.day}" class="${d.day===state.day?'active':''}" title="Day ${d.day}">${a.length<=30||i%Math.ceil(a.length/25)===0?d.day:''}</button>`).join('')}</div></div></div>`}
function insights(){const a=validDays(),totals=OS.slice(0,7).map(k=>a.reduce((s,d)=>s+(d.clicks[k]||0),0)),sum=totals.reduce((s,v)=>s+v,0),circ=2*Math.PI*50;let offset=0;return `<div class="simple-share"><div class="share-ring-v3"><svg viewBox="0 0 140 140" role="img" aria-label="生成器点击占比">${totals.map((v,i)=>{let size=v/(sum||1)*circ,old=offset;offset+=size;return `<circle cx="70" cy="70" r="50" fill="none" stroke="${COLORS[i]}" stroke-width="21" stroke-dasharray="${size} ${circ-size}" stroke-dashoffset="${-old}" transform="rotate(-90 70 70)" data-os-detail="${OS[i]}" tabindex="0" role="button" aria-label="${NAMES[i]} ${fmt(v)}次"/>`}).join('')}<text x="70" y="66" text-anchor="middle" fill="#233a58" font-size="19" font-weight="700">${fmt(sum)}</text><text x="70" y="86" text-anchor="middle" fill="#8a9aaf" font-size="12">生成次数</text></svg></div><div class="share-legend">${totals.map((v,i)=>`<button data-os-detail="${OS[i]}"><i style="background:${COLORS[i]}"></i><span>${ICONS[i]} ${NAMES[i]}</span><b>${pct(v/sum,0)}</b></button>`).join('')}</div></div>`}

function dayDetails(){let d=byDay.get(state.day)??ds()[0];if(!d)return '';state.day=d.day;return `<section class="panel section-gap"><div class="panel-head"><div class="selected-title"><span class="day-id">DAY ${d.day}</span><span class="pill">店铺 ${d.store}</span><span class="pill ${d.complete?'good':'warn'}">${d.complete?'订单已就绪':'待核对'}</span></div><button class="small primary" id="play-day">🤖 玩这一天</button></div><div class="panel-body"><div class="day-strip">${ds().map(x=>`<button data-day="${x.day}" aria-pressed="${x.day===state.day}" class="${x.day===state.day?'active':''} ${(x.clicks.os_3||0)>=256?'peak':''}">${x.day}</button>`).join('')}</div><div class="order-list">${ordersFor(d.day).map(orderCard).join('')}</div></div></section>`}
function orderCard(o){return `<article class="order-card"><div class="order-top"><button data-detail-order="${o.row}">订单 ${o.day}-${o.order} →</button><span class="order-energy"><b>${fmt(o.stamina,1)} 体力</b>${help('orderEnergy')}</span></div>${o.clean?'<div class="order-line"><span class="item-glyph">♻️</span><div><b style="font-size:.875rem">库存回收</b><small>clean 库存回收</small></div></div>'+help('clean'):''}${o.lines.map(l=>{let it=byName.get(l.name);return `<div class="order-line"><span class="item-glyph">${glyph(it)}</span><div><button data-item="${esc(l.name)}">${esc(it?.display??l.name)} ×${l.quantity}</button><small>${it?.level?`Lv.${it.level}`:'加工物'} · ${esc(l.name)}</small></div></div>`}).join('')}${o.error?'<span class="pill warn">需求拆解待核对</span>':''}<footer>表格第 ${o.row} 行 ${o.fever?' · FEVER '+help('fever'):''} · ${Object.values(o.clicks).filter(v=>v>0).length} 条生成器参与</footer></article>`}
function renderContent(){const c=$('#content');if(state.page==='overview'||state.page==='rhythm'){c.innerHTML=dataNotice()+metrics()+chartPanel()+(state.page==='overview'?`<div class="grid-2"><section class="panel"><div class="panel-head"><div><h2>每天的全部订单分布 ${help('heat')}</h2><p>颜色越深，负载越高 · 各 OS 独立归一化</p></div><span class="pill">点击联动</span></div><div class="panel-body">${heatmap()}</div></section><section class="panel"><div class="panel-head"><h2>哪类物品做得最多 ${help('mostItems')}</h2><span class="muted" style="font-size:.75rem">当前范围</span></div><div class="panel-body">${insights()}</div></section></div>`:'')+dayDetails();bindContent();afterRender()}else renderExtra()}
function bindContent(){document.querySelectorAll('[data-chart-series]').forEach(input=>input.onchange=()=>{const key=input.dataset.chartSeries;chartSeries[key]=input.checked;try{localStorage.setItem(chartSeriesStorage,JSON.stringify(chartSeries))}catch{}renderContent();document.querySelector(`[data-chart-series="${key}"]`)?.focus({preventScroll:true})});document.querySelectorAll('[data-day]').forEach(b=>{b.onclick=()=>{if(b.closest('.day-strip')){state.day=+b.dataset.day;renderContent();document.querySelector(`.day-strip [data-day="${state.day}"]`)?.focus({preventScroll:true});return}showDay(+b.dataset.day,b.dataset.dayOs)};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.onclick()}}});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;renderContent()});if($('#metric-select'))$('#metric-select').onchange=e=>{state.metric=e.target.value;renderContent()};if($('#play-day'))$('#play-day').onclick=()=>navigate('board');document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>itemDetail(b.dataset.item))}
function exportCSV(){let header=['店铺','Day','模型体力','预期体力','数据完整','数值来源',...OS.map(osLabel)],rows=ds().map(d=>[d.store,d.day,d.stamina,d.target??'',d.complete,d.recalculated?'正式递推':'历史缓存',...OS.map(k=>d.clicks[k]??'')]);download('merge-lab-days.csv','\ufeff'+[header,...rows].map(r=>r.join(',')).join('\r\n'),'text/csv;charset=utf-8');toast('已导出当前日期范围')}
function download(name,text,type){let url=URL.createObjectURL(new Blob([text],{type}));let a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
let renderExtra=()=>{$('#content').innerHTML='<div class="panel empty">正在接入此工作区…</div>'},stopBoard=()=>{},afterRender=()=>{};
function itemDetail(name){let i=byName.get(name);if(!i)return;$('#detail-body').innerHTML=`<div class="dialog-lead"><span class="item-glyph">${glyph(i)}</span><div><h2>${esc(i.display)}</h2><p class="subtitle">${esc(i.name)} · ${esc(i.mf)}</p></div></div><div class="metric-grid" style="grid-template-columns:1fr 1fr">${metric('一级等价物品',fmt(i.units),'个','物品表配置值','')}${metric('额外点击',fmt(i.extra),'次','加工与衍生产出配置','')}</div><h3>配方材料 ${help('recipe')}</h3><p class="subtitle">${i.recipe?.map(n=>`<button class="recipe-link" data-recipe-item="${esc(n)}">${esc(n)}</button>`).join(' + ')||'基础合成链；同级两个物品合并成高一级。'}</p><h3 class="section-gap">递归需求 ${help('needs')}</h3><div class="section-gap">${Object.entries(i.needs??{}).map(([k,v])=>`<div class="stat-row"><span>${esc(D.chains[k]??k)}</span><strong>${fmt(v)} 个一级等价量</strong></div>`).join('')}</div>${i.error?`<div class="notice warning">${esc(i.error)}</div>`:''}`;if(!$('#detail').open)$('#detail').showModal();document.querySelectorAll('[data-recipe-item]').forEach(b=>b.onclick=()=>{let name=b.dataset.recipeItem;let found=byName.get(name)??D.items.find(x=>x.display===name||x.key===name||x.mf===name);if(found)itemDetail(found.name);else toast('材料名称未匹配到物品表')})}
installHelp();installDetails();
$('#detail .dialog-close').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close()});
try{const response=await fetch('./data/game-data.json');if(!response.ok)throw Error('HTTP '+response.status);D=await response.json();byName=new Map(D.items.map(i=>[i.name,i]));byRow=new Map(D.orders.map(o=>[o.row,o]));byDay=new Map(D.days.map(d=>[d.day,d]));state.store=D.meta.currentStore;resetRange();render();}catch(e){$('#app').innerHTML=`<div class="loading"><h1>配置暂时无法载入</h1><p>${esc(e.message)}</p><button onclick="location.reload()">重新载入</button></div>`}

export {D,state,$,dataNotice,OS,COLORS,NAMES,ICONS,byName,byRow,byDay,fmt,pct,esc,stats,correlation,rolling,numConfig,ds,validDays,ordersFor,glyph,toast,render,renderContent,bindContent,metric,chartPanel,dayDetails,download,itemDetail};
export function installViews(fn,stop,after){renderExtra=fn;stopBoard=stop;afterRender=after??(()=>{});}
if(D)import('./views.js').then(module=>{module.registerWebMCP();if(!['overview','rhythm'].includes(state.page))renderContent()}).catch(e=>toast('附加视图载入失败：'+e.message));
