import {stats, correlation, rolling, escapeHtml as esc} from './math.js';
const $=s=>document.querySelector(s);
const COLORS=['#3d75ef','#36b3a2','#e9ac4e','#a385df','#ed8998','#6bb4cd','#5968b2','#a6b3c6'];
const OS=['os_1','os_2','os_3','os_4','os_5','os_6','os_7','被动'];
const NAMES=['衣装','鞋履箱包','茶点饮品','珠宝配饰','材料矿石','玩偶','花卉美妆','专属 OSA'];
const ICONS=['👕','👟','🍰','💎','🧵','🧸','🌷','🎁'];
const PATHS={overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',rhythm:'M3 17l5-9 5 6 8-12M3 21h18',generators:'M12 3l9 5v8l-9 5-9-5V8zM3 8l9 5 9-5M12 13v8',board:'M3 3h18v18H3zM3 9h18M3 15h18M9 3v18M15 3v18',catalog:'M4 3h6v18H4zM14 3h6v18h-6z',source:'M3 5h18v14H3zM3 10h18M9 5v14'};
const PAGES=[['overview','体验总览'],['rhythm','订单节奏'],['generators','物品产出'],['board','机器人游乐场'],['catalog','物品图鉴'],['source','数据与说明']];
let D,state={page:'overview',store:16,day:326,from:326,to:350,metric:'stamina',mode:'bars',os:'os_3',search:'',catalogPage:1};
let byName,byRow,byDay;
const fmt=(n,dec=0)=>Number.isFinite(n)?n.toLocaleString('zh-CN',{maximumFractionDigits:dec}):'—';
const pct=(n,dec=1)=>Number.isFinite(n)?`${(n*100).toFixed(dec)}%`:'—';
const icon=(key)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${PATHS[key]}"/></svg>`;
const osLabel=k=>k==='被动'?'OSA':k.replace('_','').toUpperCase();
const numConfig=(key,fallback=0)=>Number(D.config[key]??fallback);
const ds=()=>D.days.filter(d=>(state.store===0||d.store===state.store)&&d.day>=state.from&&d.day<=state.to);
const validDays=()=>ds().filter(d=>d.complete);
const ordersFor=day=>(byDay.get(Number(day))?.orders??[]).map(r=>byRow.get(r));
function glyph(item){let chain=item?.chain??Object.keys(item?.needs??{})[0]??'';return ICONS[chain.includes('_a_')?7:Math.max(0,Number(chain.split('_')[1])-1)]??'📦'}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function render(){
 const title=PAGES.find(p=>p[0]===state.page)?.[1];
 $('#app').innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brandmark">M</span><div><strong>MERGE LAB</strong><small>游戏数值实验室</small></div></div><div class="nav-label">WORKSPACE</div><nav aria-label="主导航">${PAGES.map(([id,name])=>`<button class="nav-item ${state.page===id?'active':''}" data-page="${id}" ${state.page===id?'aria-current="page"':''}>${icon(id)}${name}${id==='board'?'<span class="tiny-tag">PLAY</span>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="sidebar-note"><strong>真实配置 · 自由探索</strong>${D.meta.sheets.length} 张工作表 / ${fmt(D.items.length)} 个物品<br>7 × 8 棋盘实验</div><strong>MERGE GAME</strong>数据快照 ${new Date(D.meta.sourceModifiedAt).toLocaleDateString('zh-CN')}<br>数值逻辑.xlsx</div></aside><div class="workspace"><header class="topbar"><div class="breadcrumb">工作空间 <span>/</span> <b>${title}</b></div><div class="top-tools"><span class="status-badge">配置已载入</span><button class="small ghost" data-page="source">数据与说明</button><span class="avatar">MG</span></div></header><main class="main" id="main"><div class="page-heading"><div><div class="eyebrow">${state.page==='board'?'PLAY & EXPERIMENT':'BALANCE & PACING'}</div><h1>${title}</h1><p class="subtitle">${pageSubtitle()}</p></div><div class="heading-actions"><button class="ghost" id="export-csv">↓ 导出数据</button><button class="primary" data-page="board">🤖 看机器人玩</button></div></div>${toolbar()}<div id="content" class="fade-in"></div><footer class="page-footer"><span>MERGE LAB / 配置驱动的数值探索</span><span>当前店铺已复算 · ${fmt(D.orders.length)} 张订单 · ${D.days.length} 天 · ${new Set(D.days.map(d=>d.store)).size} 家店铺</span></footer></main></div></div>`;
 renderContent();bindShell();
}
function pageSubtitle(){return {overview:'从整店负载，到每一次合成。让配置里的节奏看得见。',rhythm:'沿着时间轴，拆解每一天、每一单的压力与释放。',generators:'观察七条生成器的参与、错峰与库存积累。',board:'把真实订单搬上棋盘，体验生成、合成、加工与交付。',catalog:'查找物品，追溯配方，看到每条产出链的需求。',source:'查看原始表格、配置参数与计算边界。'}[state.page]}
function toolbar(){let stores=[...new Set(D.days.map(d=>d.store))];return `<div class="toolbar"><label>店铺 <select id="store-select" aria-label="选择店铺"><option value="0" ${state.store===0?'selected':''}>全部店铺</option>${stores.map(n=>`<option value="${n}" ${state.store===n?'selected':''}>店铺 ${String(n).padStart(2,'0')}</option>`).join('')}</select></label><span class="divider"></span><label>DAY <input id="from-day" type="number" min="1" max="350" value="${state.from}" aria-label="开始day"> — <input id="to-day" type="number" min="1" max="350" value="${state.to}" aria-label="结束day"></label><button class="small" id="apply-range">应用</button><button class="small ghost" id="reset-range">全店范围</button><span class="spacer"></span><span class="muted" style="font-size:.75rem">${ds().length} 天 · ${fmt(ds().reduce((n,d)=>n+d.orders.length,0))} 张订单</span></div>`}
function bindShell(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$('#store-select').onchange=e=>{state.store=+e.target.value;resetRange();render()};$('#apply-range').onclick=()=>{let a=+$('#from-day').value,b=+$('#to-day').value;if(a>b||!D.days.some(d=>d.day>=a&&d.day<=b&&(state.store===0||d.store===state.store))){toast('请选择有数据的日期范围');return}state.from=a;state.to=b;state.day=ds()[0].day;render()};$('#reset-range').onclick=()=>{resetRange();render()};$('#export-csv').onclick=exportCSV}
function navigate(page){state.page=page;if(page!=='board')stopBoard?.();render()}
function resetRange(){let a=D.days.filter(d=>state.store===0||d.store===state.store);state.from=a[0].day;state.to=a.at(-1).day;state.day=a[0].day}

function dataNotice(){let a=ds(),fresh=a.filter(d=>d.recalculated).length;return `<div class="data-note"><span>ⓘ ${fresh===a.length?'当前店铺已复算':fresh?`${fresh}天已复算，其余为历史数据`:'历史数据快照'}</span><span class="data-note-detail">详细说明见数据与说明</span></div>`}

function metrics(){let a=validDays(),s=stats(a.map(d=>d.stamina)),orders=a.reduce((n,d)=>n+d.orders.length,0);return `<div class="metric-grid">${metric('订单总数',fmt(orders),'单',`${a.length} 天`,'📦')}${metric('需要多少体力',fmt(s.sum),'',`每天约 ${fmt(s.mean)} 体力`,'⚡')}${metric('最忙的一天',fmt(s.max),'体力','柱子越高，当天越忙','↗')}${metric('平均每单',fmt(s.sum/orders,1),'体力','按当前范围计算','◷')}</div>`}
function metric(label,value,unit,foot,symbol){return `<article class="metric"><div class="metric-top">${label}<span class="metric-symbol">${symbol}</span></div><div class="metric-value num">${value}${unit?`<small>${unit}</small>`:''}</div><div class="metric-foot">${foot}</div></article>`}
function valueFor(d){return state.metric==='stamina'?d.stamina:(d.clicks[state.metric]??0)}
function chart(){let a=ds(),W=1000,H=252,L=52,R=14,T=16,B=34,cw=W-L-R,ch=H-T-B;let vals=a.map(valueFor),max=Math.max(1,...vals,...(state.metric==='stamina'?a.map(d=>d.target??0):[]))*1.1;let step=cw/a.length,x=i=>L+(i+.5)*step,y=v=>T+ch-v/max*ch;let ma=rolling(vals,3);return `<div class="chart-wrap"><svg class="chart-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="每日${state.metric==='stamina'?'体力':osLabel(state.metric)+'点击'}图，可点击柱形选择day"><defs><linearGradient id="bar-grad" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#4b80f3"/><stop offset="1" stop-color="#9abbff"/></linearGradient></defs>${[0,1,2,3,4].map(n=>`<line x1="${L}" x2="${W-R}" y1="${y(max*n/4)}" y2="${y(max*n/4)}" stroke="#eaf0f7" stroke-dasharray="3 5"/><text x="${L-12}" y="${y(max*n/4)+4}" text-anchor="end">${fmt(max*n/4)}</text>`).join('')}${state.mode==='bars'?a.map((d,i)=>`<g class="day-hit" data-day="${d.day}" tabindex="0" role="button" aria-label="选择Day ${d.day}"><rect x="${L+i*step}" y="${T}" width="${step}" height="${ch}" fill="transparent"/><rect class="bar" x="${x(i)-step*.31}" y="${y(vals[i])}" width="${Math.max(1,step*.62)}" height="${ch-(y(vals[i])-T)}" rx="${Math.min(4,step*.15)}" fill="${!d.complete?'#c4ccd8':d.day===state.day?'#3168ed':'url(#bar-grad)'}"/><title>Day ${d.day} · ${fmt(vals[i],2)}${d.target?` · 目标 ${d.target}`:''}${!d.complete?' · 数据待核对':''}</title></g>`).join(''):`<polyline points="${vals.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" fill="none" stroke="#3d75ef" stroke-width="2.8"/>`}${state.metric==='stamina'?`<polyline points="${a.map((d,i)=>d.target==null?'':`${x(i)},${y(d.target)}`).join(' ')}" fill="none" stroke="#f0b35c" stroke-width="1.7" stroke-dasharray="4 4"/>`:''}<polyline points="${ma.map((v,i)=>`${x(i)},${y(v)}`).join(' ')}" fill="none" stroke="#1cac9c" stroke-width="2.5"/>${a.map((d,i)=>i%Math.max(1,Math.ceil(a.length/14))===0||i===a.length-1?`<text x="${x(i)}" y="${H-9}" text-anchor="middle">${d.day}</text>`:'').join('')}<text x="${W-R}" y="${H-9}" text-anchor="end"></text></svg></div>`}
function chartPanel(){return `<section class="panel"><div class="panel-head"><div><h2>每天需要多少体力</h2><p>体力负载与三日移动均值 · 点击柱形查看当天订单</p></div><div class="segment"><button class="${state.mode==='bars'?'active':''}" data-mode="bars">柱形</button><button class="${state.mode==='line'?'active':''}" data-mode="line">趋势</button></div></div><div class="panel-body"><div class="split" style="margin:0 0 18px"><div class="legend"><span><i style="background:#6b99f8"></i>${state.metric==='stamina'?'体力':osLabel(state.metric)+'点击'}</span><span><i style="background:#1cac9c"></i>近期趋势</span><span><i style="background:#f0b35c"></i>计划体力</span></div><select id="metric-select" aria-label="图表指标"><option value="stamina">全部体力</option>${OS.map(k=>`<option value="${k}" ${state.metric===k?'selected':''}>${osLabel(k)} 点击</option>`).join('')}</select></div>${chart()}</div><div class="chart-footer"><span>DAY ${state.from}—${state.to} <span style="margin:0 10px">/</span> ${ds().length} 天</span><span>峰值 <strong>${fmt(Math.max(...validDays().map(valueFor),0),1)}</strong> <span style="margin:0 9px">·</span> 点击柱子查看订单</span></div></section>`}
function heatmap(){let a=ds();return `<div class="scroll-x"><div class="heatmap" style="--cols:${a.length};min-width:${Math.max(500,a.length*20+52)}px">${OS.slice(0,7).map((k,j)=>{let max=Math.max(1,...a.map(d=>d.clicks[k]||0));return `<div class="heatrow"><span class="heat-label">${ICONS[j]} ${osLabel(k)}</span>${a.map(d=>`<button class="heat" data-day="${d.day}" aria-label="Day ${d.day} ${osLabel(k)} ${fmt(d.clicks[k],1)}点击" title="Day ${d.day} · ${osLabel(k)} ${fmt(d.clicks[k],1)}" style="background:color-mix(in srgb,${COLORS[j]} ${12+(d.clicks[k]||0)/max*83}%,white)"></button>`).join('')}</div>`}).join('')}<div class="heatrow days"><span></span>${a.map((d,i)=>`<button data-day="${d.day}" class="${d.day===state.day?'active':''}" title="Day ${d.day}">${a.length<=30||i%Math.ceil(a.length/25)===0?d.day:''}</button>`).join('')}</div></div></div>`}
function insights(){let a=validDays(),totals=OS.slice(0,7).map(k=>a.reduce((s,d)=>s+(d.clicks[k]||0),0)),sum=totals.reduce((s,v)=>s+v,0),stop=0;const segments=totals.map((v,i)=>{let start=stop;stop+=v/(sum||1)*100;return `${COLORS[i]} ${start}% ${stop}%`}).join(',');return `<div class="simple-share"><div class="share-ring" style="background:conic-gradient(${segments})" role="img" aria-label="七类生成器点击占比"><span><b>${fmt(sum)}</b>生成次数</span></div><div class="share-legend">${totals.map((v,i)=>`<div><i style="background:${COLORS[i]}"></i><span>${ICONS[i]} ${NAMES[i]}</span><b>${pct(v/sum,0)}</b></div>`).join('')}</div></div>`}
function dayDetails(){let d=byDay.get(state.day)??ds()[0];if(!d)return '';state.day=d.day;return `<section class="panel section-gap"><div class="panel-head"><div class="selected-title"><span class="day-id">DAY ${d.day}</span><span class="pill">店铺 ${d.store}</span><span class="pill ${d.complete?'good':'warn'}">${d.complete?'订单已就绪':'待核对'}</span></div><button class="small primary" id="play-day">🤖 玩这一天</button></div><div class="panel-body"><div class="day-strip">${ds().map(x=>`<button data-day="${x.day}" class="${x.day===state.day?'active':''} ${(x.clicks.os_3||0)>=256?'peak':''}">${x.day}</button>`).join('')}</div><div class="order-list">${ordersFor(d.day).map(orderCard).join('')}</div></div></section>`}
function orderCard(o){return `<article class="order-card"><div class="order-top"><strong>订单 ${o.day}-${o.order}</strong><span>${fmt(o.stamina,1)} ϟ</span></div>${o.clean?'<div class="order-line"><span class="item-glyph">♻️</span><div><b style="font-size:.875rem">库存回收</b><small>clean 固定订单</small></div></div>':''}${o.lines.map(l=>{let it=byName.get(l.name);return `<div class="order-line"><span class="item-glyph">${glyph(it)}</span><div><button data-item="${esc(l.name)}">${esc(it?.display??l.name)} ×${l.quantity}</button><small>${it?.level?`Lv.${it.level}`:'加工物'} · ${esc(l.name)}</small></div></div>`}).join('')}${o.error?'<span class="pill warn">需求拆解待核对</span>':''}<footer>表格第 ${o.row} 行 ${o.fever?' · FEVER':''} · ${Object.values(o.clicks).filter(v=>v>0).length} 条生成器参与</footer></article>`}
function renderContent(){const c=$('#content');if(state.page==='overview'||state.page==='rhythm'){c.innerHTML=dataNotice()+metrics()+chartPanel()+(state.page==='overview'?`<div class="grid-2"><section class="panel"><div class="panel-head"><div><h2>每天在做什么</h2><p>颜色越深，负载越高 · 各 OS 独立归一化</p></div><span class="pill">点击联动</span></div><div class="panel-body">${heatmap()}</div></section><section class="panel"><div class="panel-head"><h2>哪类物品做得最多</h2><span class="muted" style="font-size:.75rem">当前范围</span></div><div class="panel-body">${insights()}</div></section></div>`:'')+dayDetails();bindContent();afterRender()}else renderExtra()}
function bindContent(){document.querySelectorAll('[data-day]').forEach(b=>{b.onclick=()=>{state.day=+b.dataset.day;renderContent()};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.onclick()}}});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;renderContent()});if($('#metric-select'))$('#metric-select').onchange=e=>{state.metric=e.target.value;renderContent()};if($('#play-day'))$('#play-day').onclick=()=>navigate('board');document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>itemDetail(b.dataset.item))}
function exportCSV(){let header=['店铺','Day','模型体力','预期体力','数据完整','数值来源',...OS.map(osLabel)],rows=ds().map(d=>[d.store,d.day,d.stamina,d.target??'',d.complete,d.recalculated?'正式递推':'历史缓存',...OS.map(k=>d.clicks[k]??'')]);download('merge-lab-days.csv','\ufeff'+[header,...rows].map(r=>r.join(',')).join('\r\n'),'text/csv;charset=utf-8');toast('已导出当前日期范围')}
function download(name,text,type){let url=URL.createObjectURL(new Blob([text],{type}));let a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
let renderExtra=()=>{$('#content').innerHTML='<div class="panel empty">正在接入此工作区…</div>'},stopBoard=()=>{},afterRender=()=>{};
function itemDetail(name){let i=byName.get(name);if(!i)return;$('#detail-body').innerHTML=`<div class="dialog-lead"><span class="item-glyph">${glyph(i)}</span><div><h2>${esc(i.display)}</h2><p class="subtitle">${esc(i.name)} · ${esc(i.mf)}</p></div></div><div class="metric-grid" style="grid-template-columns:1fr 1fr">${metric('一级等价物品',fmt(i.units),'个','物品表配置值','')}${metric('额外点击',fmt(i.extra),'次','加工与衍生产出配置','')}</div><h3>配方材料</h3><p class="subtitle">${i.recipe?.map(n=>`<button class="recipe-link" data-recipe-item="${esc(n)}">${esc(n)}</button>`).join(' + ')||'基础合成链；同级两个物品合并成高一级。'}</p><h3 class="section-gap">递归需求</h3><div class="section-gap">${Object.entries(i.needs??{}).map(([k,v])=>`<div class="stat-row"><span>${esc(D.chains[k]??k)}</span><strong>${fmt(v)} 个一级等价量</strong></div>`).join('')}</div>${i.error?`<div class="notice warning">${esc(i.error)}</div>`:''}`;if(!$('#detail').open)$('#detail').showModal();document.querySelectorAll('[data-recipe-item]').forEach(b=>b.onclick=()=>{let name=b.dataset.recipeItem;let found=byName.get(name)??D.items.find(x=>x.display===name||x.key===name||x.mf===name);if(found)itemDetail(found.name);else toast('材料名称未匹配到物品表')})}
$('#detail .dialog-close').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close()});
try{const response=await fetch('./data/game-data.json');if(!response.ok)throw Error('HTTP '+response.status);D=await response.json();byName=new Map(D.items.map(i=>[i.name,i]));byRow=new Map(D.orders.map(o=>[o.row,o]));byDay=new Map(D.days.map(d=>[d.day,d]));state.store=D.meta.currentStore;resetRange();render();}catch(e){$('#app').innerHTML=`<div class="loading"><h1>配置暂时无法载入</h1><p>${esc(e.message)}</p><button onclick="location.reload()">重新载入</button></div>`}

export {D,state,$,dataNotice,OS,COLORS,NAMES,ICONS,byName,byRow,byDay,fmt,pct,esc,stats,correlation,rolling,numConfig,ds,validDays,ordersFor,glyph,toast,render,renderContent,bindContent,metric,chartPanel,dayDetails,download,itemDetail};
export function installViews(fn,stop,after){renderExtra=fn;stopBoard=stop;afterRender=after??(()=>{});}
if(D)import('./views.js').then(module=>{module.registerWebMCP();if(!['overview','rhythm'].includes(state.page))renderContent()}).catch(e=>toast('附加视图载入失败：'+e.message));
