import {D,state,$,OS,NAMES,ICONS,byName,fmt,esc,glyph,toast,download,itemDetail,itemLineText} from './app.js';
import {RobotSimulator} from './robot.js';
import {DEFAULT_PLAN,MAX_PLAN_ORDERS,PLAN_MODES,defaultOrders,validateOrders,validatePlan} from './workflow.js';
import {help,showHelp} from './explain.js';
const memory=new Map(),key=day=>`merge-lab-scenario-v4:${day}`;
let editorOrders=[],editorPlan=[],editorIndex=0,editorQuery='',editorDirty=false,context=null;
export function loadScenario(day=state.day){let saved=memory.get(day);if(!saved){try{saved=JSON.parse(localStorage.getItem(key(day))||localStorage.getItem(`merge-lab-scenario-v3:${day}`)||'null')}catch{}}const base={version:4,day,plan:DEFAULT_PLAN,warehouseCapacity:7,cd:{},seed:20260917};if(!saved)return base;try{return validateScenario({...base,...saved},day)}catch{return base}}
export function validateScenario(s,day){if(![3,4].includes(s.version)||s.day!==day)throw Error('场景版本或日期不匹配');let inputPlan=s.plan;if(s.version===3){if(!Array.isArray(inputPlan)||!inputPlan.length||inputPlan.length>30||inputPlan.some(p=>!p||!Object.hasOwn(PLAN_MODES,p.mode)||!Number.isInteger(p.repeat)||p.repeat<1||p.repeat>999))throw Error('旧版计划无效');inputPlan=inputPlan.slice(0,MAX_PLAN_ORDERS).map(p=>({mode:p.mode}))}const plan=validatePlan(inputPlan);if(!Number.isInteger(s.warehouseCapacity)||s.warehouseCapacity<0||s.warehouseCapacity>200)throw Error('仓库容量必须为0到200格');const cd={};for(const k of OS){let c=s.cd?.[k]??{mode:'unlimited',batch:20,seconds:60};if(!['unlimited','configured'].includes(c.mode)||!Number.isInteger(c.batch)||c.batch<1||c.batch>10000||!Number.isFinite(c.seconds)||c.seconds<0||c.seconds>86400)throw Error('CD参数无效');cd[k]={mode:c.mode,batch:c.batch,seconds:c.seconds}}if(s.initial)RobotSimulator.prototype.validateOpening.call({items:new Map(D.items.map(i=>[i.name,i])),day:D.days.find(d=>d.day===day)},s.initial.layout,s.initial.energy);return {...(s.initial?{initial:{layout:[...s.initial.layout],energy:s.initial.energy}}:{}),version:4,day,plan,warehouseCapacity:s.warehouseCapacity,cd,seed:Number.isInteger(s.seed)?s.seed>>>0:20260917,...(s.orders?{orders:validateOrders(D,day,s.orders)}:{})}}
function savePatch(patch){const settings={...loadScenario(),...patch,version:4,day:state.day};memory.set(state.day,settings);try{localStorage.setItem(key(state.day),JSON.stringify(settings))}catch{toast('已应用；此浏览器不允许持久保存')}return settings}
export function workflowPanel(sim){return `<section class="panel workflow-panel"><div class="panel-head"><h2>机器人计划 ${help('plan')}</h2><button class="small" id="workflow-edit">设置计划</button></div><div class="panel-body"><div class="workflow-stages" id="workflow-stages">${stageList(sim)}</div><p class="workflow-frequency">一行一单 · 最多7行 · 完成后停止</p><div class="workflow-current" id="workflow-current"></div></div></section>`}
function stageList(sim){return sim.plan.map((p,i)=>{const done=i<sim.planIndex,active=i===sim.planIndex&&!sim.complete(),order=sim.orders.find(o=>o.id===sim.planOrders[i]);return `<div class="workflow-stage ${active?'active':''} ${done?'done':''}" title="${esc(order?.title??'执行到这里时按倾向选择1张订单')}"><span>${done?'✓':i+1}</span><b>${PLAN_MODES[p.mode]}</b><small>${done?'已完成':active&&order?'进行中':sim.ordersComplete()?'无剩余订单':'待执行'}</small></div>`}).join('')}
export function paintWorkflow(sim){const stages=$('#workflow-stages'),html=stageList(sim);if(stages&&stages.dataset.signature!==html){stages.innerHTML=html;stages.dataset.signature=html}setText($('#workflow-current'),sim.current()?`计划 ${sim.planIndex+1}/${sim.plan.length}：${sim.current().title}`:sim.ordersComplete()?'当日订单已全部交付':sim.planComplete()?`已完成 ${sim.plan.length}/${sim.plan.length} 行，机器人已停止`:`下一行 ${sim.planIndex+1}/${sim.plan.length}：${PLAN_MODES[sim.plan[sim.planIndex].mode]}`)}
function setText(node,text){if(node&&node.textContent!==String(text))node.textContent=String(text)}
export function warehousePanel(){return `<section class="warehouse-panel"><div class="warehouse-head"><h2>仓库 ${help('warehouse')}</h2><label>容量 <input id="warehouse-capacity" type="number" min="0" max="200" value="7" aria-label="仓库容量"><button class="small" id="warehouse-resize">应用</button></label></div><div class="warehouse-grid" id="warehouse-grid"></div><small class="muted">点棋盘物品可存入；点仓库物品可取回</small></section>`}
export function paintWarehouse(sim,manual){if(!$('#warehouse-grid'))return;const input=$('#warehouse-capacity');if(document.activeElement!==input)input.value=sim.warehouse.length;$('#warehouse-grid').innerHTML=sim.warehouse.map((t,i)=>`<button class="warehouse-cell ${t?'filled':''}" data-warehouse="${i}" aria-label="仓库第${i+1}格：${esc(byName.get(t?.name)?.display??'空位')}" title="${esc(byName.get(t?.name)?.display??'空位')}">${t?`<span>${glyph(byName.get(t.name))}</span><small>${byName.get(t.name)?.level?'L'+byName.get(t.name).level:'✦'}</small>`:'·'}</button>`).join('')||'<p class="muted">仓库容量为0</p>';document.querySelectorAll('[data-warehouse]').forEach(b=>b.onclick=()=>{const i=+b.dataset.warehouse;if(sim.warehouse[i])manual(()=>sim.execute(sim.retrievePlan(i,'手动从仓库取回物品')))})}
export function orderPool(sim){
  return `<div class="pool-summary"><span id="pool-delivered"></span><strong>🪙 <span id="pool-coins"></span> <small>累计金币 ${help('coins')}</small></strong></div><div class="reward-notice">金币：演示值或手动设置，非工作簿输入 ${help('rewardSource')}</div><div class="active-order-summary"><div><b id="pool-current-title"></b><span id="pool-current-percent"></span></div><div class="mini-track" role="progressbar" aria-label="当前订单预计完成度" aria-valuemin="0" aria-valuemax="100" id="pool-current-bar"><span></span></div><div class="active-order-caption"><span id="pool-current-remaining"></span><span>预计完成度 ${help('orderProgress')}</span></div><div class="active-order-needs" id="pool-current-needs"></div></div><div class="pool-progress-caption">成品数量：已有 / 需要 ${help('readyItems')}</div><div class="order-pool" tabindex="0" aria-label="全部订单及实时进度">${sim.orders.map(o=>`<button class="pool-order" data-pool-order="${esc(o.id)}"><div><b>${esc(o.title)}</b><span data-order-status></span></div><div class="pool-items">${o.lines.map((l,i)=>`<span class="pool-material"><span class="material-glyph">${glyph(byName.get(l.name))}</span><span class="material-copy"><b>${esc(byName.get(l.name)?.display??l.name)}</b><span class="item-lineage">${esc(itemLineText(l.name))}</span></span><small data-need-index="${i}"></small></span>`).join('')||'♻ 回收'}</div><footer><span>🪙 ${fmt(o.reward)} <small>${o.rewardSource==='demo'?'演示值':'手动'}</small></span><span data-order-remaining></span></footer><div class="pool-progress-label"><span>预计完成度</span><b data-order-percent></b></div><div class="mini-track" role="progressbar" aria-label="${esc(o.title)}预计完成度" aria-valuemin="0" aria-valuemax="100"><span></span></div></button>`).join('')}</div><div class="pool-action"><button id="robot-submit" class="full primary" hidden>交付当前订单</button><p id="pool-stop-note" class="workflow-frequency"></p><button class="primary full" id="robot-next-day" hidden>下一天 →</button></div>`;
}
export function paintOrderPool(sim){
  const current=sim.current(),evaluations=new Map(sim.evaluations().map(e=>[e.id,e])),stock=sim.allStock();
  setText($('#pool-delivered'),`已交付 ${sim.delivered}/${sim.orders.length}`);setText($('#pool-coins'),fmt(sim.coins));
  document.querySelectorAll('[data-pool-order]').forEach(card=>{const o=sim.orders.find(o=>o.id===card.dataset.poolOrder),done=sim.completedIds.includes(o.id),active=o.id===sim.activeId,e=evaluations.get(o.id),percent=done?100:Math.floor((e?.progress??0)*100);card.classList.toggle('active',active);card.classList.toggle('done',done);setText(card.querySelector('[data-order-status]'),done?'✓ 已交付':active?'正在完成':o.error?'需核对':'待选择');setText(card.querySelector('[data-order-remaining]'),done?'已完成':Number.isFinite(e?.remaining)?`还需约 ${fmt(e.remaining)} 体力`:'无法估算 · 点开查看');setText(card.querySelector('[data-order-percent]'),`${percent}%`);const bar=card.querySelector('.mini-track');bar.setAttribute('aria-valuenow',percent);bar.firstElementChild.style.width=`${percent}%`;card.querySelectorAll('[data-need-index]').forEach(node=>{const l=o.lines[+node.dataset.needIndex],count=done?l.quantity:Math.min(stock[l.name]||0,l.quantity);setText(node,`${count}/${l.quantity}`);node.parentElement.classList.toggle('ready',count===l.quantity)})});
  const e=evaluations.get(current?.id),percent=current?Math.floor((e?.progress??0)*100):sim.complete()?100:0;
  setText($('#pool-current-title'),current?`正在做：${current.title}`:sim.ordersComplete()?'当日订单全部完成':sim.planComplete()?'计划已完成，自动停止':'等待按计划选择订单');setText($('#pool-current-percent'),`${percent}%`);const bar=$('#pool-current-bar');bar.setAttribute('aria-valuenow',percent);bar.firstElementChild.style.width=`${percent}%`;
  setText($('#pool-current-remaining'),current?(Number.isFinite(e?.remaining)?`还需约 ${fmt(e.remaining)} 体力`:'需求配置待核对'):sim.complete()?`已交付 ${sim.delivered} 单`:'点播放开始');
  const needs=$('#pool-current-needs'),activeKey=current?.id??'';
  if(needs.dataset.order!==activeKey){needs.dataset.order=activeKey;needs.innerHTML=current?(current.lines.map((l,i)=>`<span class="active-material"><span class="material-copy"><span>${glyph(byName.get(l.name))} ${esc(byName.get(l.name)?.display??l.name)}</span><span class="item-lineage">${esc(itemLineText(l.name))}</span></span><b data-current-need="${i}"></b></span>`).join('')||'<span>♻ 库存回收</span>'):''}
  needs.querySelectorAll('[data-current-need]').forEach(node=>{const l=current.lines[+node.dataset.currentNeed],count=Math.min(stock[l.name]||0,l.quantity);setText(node,`${count}/${l.quantity}`);node.parentElement.classList.toggle('ready',count===l.quantity)});
  const submit=$('#robot-submit');submit.hidden=!current;submit.disabled=!current||!sim.indicesFor(sim.demands());setText(submit,submit.disabled?'准备物品中…':'交付当前订单');$('#robot-next-day').hidden=!sim.ordersComplete();
  const note=$('#pool-stop-note');note.hidden=!!current;setText(note,sim.ordersComplete()?'当日订单已全部交付 ✓':sim.planComplete()?`已完成设置的 ${sim.plan.length} 单，剩余 ${sim.pending().length} 单未执行${sim.plan.length<MAX_PLAN_ORDERS?'；可在设置计划中添加下一行':''}。`:'按计划选1张订单，完成后再执行下一行。');
}
export function bindPool(sim){document.querySelectorAll('[data-pool-order]').forEach(b=>b.onclick=()=>showOrder(sim,b.dataset.poolOrder))}
function showOrder(sim,id){const o=sim.orders.find(o=>o.id===id),e=sim.evaluations().find(e=>e.id===id);if(!o)return;$('#detail-body').innerHTML=`<h2>${esc(o.title)}</h2><div class="order-detail-values"><b>🪙 ${o.reward} ${help('reward')}<small>${o.rewardSource==='demo'?'演示值 · 非表格输入':'手动设置'}</small></b><b>${fmt(e?.remaining)} 体力<small>预计还需体力 ${help('remaining')}</small></b></div>${o.lines.map(l=>`<button class="detail-ingredient" data-wf-item="${esc(l.name)}">${glyph(byName.get(l.name))} ${esc(byName.get(l.name)?.display??l.name)} ×${l.quantity}<small class="item-lineage">${esc(itemLineText(l.name))}</small></button>`).join('')}${o.error?`<p class="notice warning">${esc(o.error)}；请在订单编辑中修改或移除这张订单。</p>`:''}${o.clean?'<p>包含库存回收 '+help('clean')+'</p>':''}<p class="workflow-frequency">完成度基于现有棋盘和仓库库存；点击物品查看配方。</p>`;document.querySelectorAll('[data-wf-item]').forEach(b=>b.onclick=()=>itemDetail(b.dataset.wfItem));if(!$('#detail').open)$('#detail').showModal()}
export function settingsPanel(){return `<section class="panel"><div class="panel-body" style="padding-top:16px"><div class="scenario-buttons"><button id="pool-edit">编辑订单需求 / 奖励</button><span><button id="generator-settings">生成器CD设置</button>${help('cd')}</span></div><div class="scenario-buttons"><span><button id="scenario-export" class="small ghost">导出场景</button>${help('sceneExport')}</span><span><button id="scenario-import" class="small ghost">导入场景</button>${help('sceneImport')}</span></div><input type="file" id="scenario-file" accept="application/json,.json" hidden></div></section>`}
export function bindWorkflow(ctx){context=ctx;const sim=ctx.sim;
  if($('#workflow-edit'))$('#workflow-edit').onclick=()=>editPlan(sim);
  if($('#pool-edit'))$('#pool-edit').onclick=()=>editPool(sim);
  if($('#warehouse-resize'))$('#warehouse-resize').onclick=()=>{try{sim.resizeWarehouse(Number($('#warehouse-capacity').value));savePatch({warehouseCapacity:sim.warehouse.length});ctx.paint()}catch(e){toast(e.message)}};
  if($('#generator-settings'))$('#generator-settings').onclick=editCD;
  if($('#scenario-export'))$('#scenario-export').onclick=()=>{const s={...loadScenario(),orders:sim.orders,plan:sim.plan,warehouseCapacity:sim.warehouse.length,initial:ctx.initial()};download(`merge-scenario-day-${state.day}.json`,JSON.stringify(s,null,2),'application/json')};
  if($('#scenario-import'))$('#scenario-import').onclick=()=>$('#scenario-file').click();
  if($('#scenario-file'))$('#scenario-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>1024*1024)throw Error('场景文件不能超过1MB');const s=validateScenario(JSON.parse(await file.text()),state.day);savePatch(s);ctx.restart(s.initial);toast('场景已导入，从初始棋盘重新开始')}catch(error){toast('导入失败：'+error.message)}};
}
function editPlan(sim){context.stop();editorPlan=sim.plan.map(p=>({...p}));const locked=sim.lockedPlanRows();const draw=()=>{
  $('#detail-body').innerHTML=`<h2>设置机器人计划 ${help('plan','设置机器人计划')}</h2><p class="workflow-frequency">每行只完成1个订单，最多7行。全部完成后自动停止。</p><div class="plan-editor">${editorPlan.map((p,i)=>`<div class="plan-edit-row"><b>${i+1}</b><select data-plan-mode="${i}" aria-label="计划${i+1}选单倾向" ${i<locked?'disabled':''}>${Object.entries(PLAN_MODES).map(([k,v])=>`<option value="${k}" ${p.mode===k?'selected':''}>${v}</option>`).join('')}</select><small>${i<sim.planIndex?'✓ 已完成':i<locked?'正在执行':'完成1单'}</small><button data-plan-up="${i}" ${i<=locked?'disabled':''} aria-label="上移计划">↑</button><button data-plan-remove="${i}" ${editorPlan.length===1||i<locked?'disabled':''} aria-label="删除计划">×</button></div>`).join('')}</div><div class="editor-save"><button id="plan-add" ${editorPlan.length>=MAX_PLAN_ORDERS?'disabled':''}>＋ 添加计划（${editorPlan.length}/7）</button><button id="plan-save" class="primary">保存计划</button></div><p class="workflow-frequency">金币优先选奖励最高；易完成优先选剩余体力最少；随机选1单。已执行和正在执行的行保留，后续行可随时调整。重开后可重新设置全部计划。</p>`;
  document.querySelectorAll('[data-plan-mode]').forEach(b=>b.onchange=()=>editorPlan[+b.dataset.planMode].mode=b.value);document.querySelectorAll('[data-plan-remove]').forEach(b=>b.onclick=()=>{const i=+b.dataset.planRemove;if(i<locked||editorPlan.length===1)return;editorPlan.splice(i,1);draw()});document.querySelectorAll('[data-plan-up]').forEach(b=>b.onclick=()=>{const i=+b.dataset.planUp;if(i<=locked)return;[editorPlan[i-1],editorPlan[i]]=[editorPlan[i],editorPlan[i-1]];draw()});$('#plan-add').onclick=()=>{if(editorPlan.length>=MAX_PLAN_ORDERS)return;editorPlan.push({mode:'value'});draw()};$('#plan-save').onclick=()=>{try{sim.setPlan(editorPlan);savePatch({plan:sim.plan});$('#detail').close();context.paint();toast('计划已保存，每行完成1单后推进，最后一行完成后停止')}catch(e){toast(e.message)}};
  };draw();if(!$('#detail').open)$('#detail').showModal();
}
function editPool(sim){context.stop();editorOrders=JSON.parse(JSON.stringify(sim.orders));editorIndex=0;editorDirty=false;drawPoolEditor();if(!$('#detail').open)$('#detail').showModal()}
function drawPoolEditor(){
  const o=editorOrders[editorIndex];$('#detail-body').innerHTML=`<h2>编辑订单池 ${help('editPool')}</h2><div class="pool-editor-top"><select id="edit-order-select" aria-label="选择编辑订单">${editorOrders.map((x,i)=>`<option value="${i}" ${i===editorIndex?'selected':''}>${esc(x.title)}</option>`).join('')}</select><button id="add-order">＋ 新订单</button><button id="delete-order" ${editorOrders.length===1?'disabled':''}>删除这单</button></div><div class="order-edit-fields"><label>订单名称<input id="order-title" maxlength="100" value="${esc(o.title)}"></label><label>金币奖励 ${help('reward')}<input id="order-reward" type="number" min="0" max="100000000" value="${o.reward}"></label></div><span class="reward-source" id="reward-source">${o.rewardSource==='demo'?'演示值 · 非表格输入':'手动设置'}</span><div class="edit-needs">${o.lines.map((l,i)=>`<div><span>${glyph(byName.get(l.name))} ${esc(byName.get(l.name)?.display??l.name)}<small class="item-lineage">${esc(itemLineText(l.name))}</small></span><input type="number" min="1" max="99" value="${l.quantity}" data-need-count="${i}" aria-label="${esc(l.name)}数量"><button data-need-remove="${i}" aria-label="删除需求">×</button></div>`).join('')||'<p class="workflow-frequency">请选择需求物品</p>'}</div><input id="order-item-search" type="search" placeholder="搜索并添加需求物品" aria-label="搜索订单需求" value="${esc(editorQuery)}"><div id="order-item-results" class="order-item-results"></div><label class="workflow-frequency"><input id="order-clean" type="checkbox" ${o.clean?'checked':''}> 包含库存回收 ${help('clean')}</label><p class="workflow-frequency">生成效率沿用这单的配置；新增订单沿用当前日第一单的效率。保存需求后从初始棋盘重新开始。</p><div class="editor-save"><button id="restore-sheet-orders">恢复导表订单</button><button id="save-order-pool" class="primary">保存订单池并重开</button></div>`;
  $('#order-title').oninput=e=>{o.title=e.target.value;editorDirty=true};$('#order-reward').oninput=e=>{o.reward=Number(e.target.value);o.rewardSource='manual';$('#reward-source').textContent='手动设置';editorDirty=true};$('#order-clean').onchange=e=>{o.clean=e.target.checked;editorDirty=true};
  document.querySelectorAll('[data-need-count]').forEach(b=>b.oninput=()=>{o.lines[+b.dataset.needCount].quantity=Number(b.value);editorDirty=true});document.querySelectorAll('[data-need-remove]').forEach(b=>b.onclick=()=>{o.lines.splice(+b.dataset.needRemove,1);editorDirty=true;drawPoolEditor()});$('#edit-order-select').onchange=e=>{editorIndex=+e.target.value;drawPoolEditor()};$('#add-order').onclick=()=>{if(editorOrders.length>=100)return;const template=defaultOrders(D,state.day)[0];editorOrders.push({...template,id:'manual-'+Date.now()+'-'+editorOrders.length,title:'自定义订单 '+(editorOrders.length+1),lines:[],reward:100,rewardSource:'demo',source:'manual',clean:false,error:null});editorIndex=editorOrders.length-1;drawPoolEditor()};$('#delete-order').onclick=()=>{editorOrders.splice(editorIndex,1);editorIndex=Math.min(editorIndex,editorOrders.length-1);drawPoolEditor()};$('#restore-sheet-orders').onclick=()=>{editorOrders=defaultOrders(D,state.day);editorIndex=0;drawPoolEditor()};$('#order-item-search').oninput=e=>{editorQuery=e.target.value;drawItemResults(o)};$('#save-order-pool').onclick=()=>{try{const orders=validateOrders(D,state.day,editorOrders);savePatch({orders});$('#detail').close();context.restart();toast('已保存手动订单池，开始新一局')}catch(e){toast(e.message)}};drawItemResults(o);
}
function drawItemResults(o){const store=context.sim.day.store,items=D.items.filter(i=>!i.error&&(!i.store||i.store===store)&&(!i.recipeStore||!/^\d+$/.test(i.recipeStore)||+i.recipeStore<=store)&&(!editorQuery||`${i.display} ${i.name} ${itemLineText(i)}`.toLowerCase().includes(editorQuery.toLowerCase()))).slice(0,18);$('#order-item-results').innerHTML=items.map(i=>`<button data-add-need="${esc(i.name)}">${glyph(i)} ${esc(i.display)}<small class="item-lineage">${esc(itemLineText(i))}</small></button>`).join('');document.querySelectorAll('[data-add-need]').forEach(b=>b.onclick=()=>{const exists=o.lines.find(l=>l.name===b.dataset.addNeed);if(exists)exists.quantity++;else o.lines.push({name:b.dataset.addNeed,quantity:1});drawPoolEditor()})}
function editCD(){const settings=loadScenario(),cd={};OS.forEach(k=>cd[k]={...(settings.cd[k]??{mode:'unlimited',batch:20,seconds:60})});$('#detail-body').innerHTML=`<h2>生成器冷却设置 ${help('cd','生成器冷却设置')}</h2><p class="cd-placeholder">预留配置：本版仅保存，不执行冷却或点击上限。默认无限生成。</p><div class="cd-table"><div class="cd-row header"><span>生成器</span><span>模式</span><span>每轮点击</span><span>冷却秒数</span></div>${OS.map((k,i)=>`<div class="cd-row"><span>${ICONS[i]} OS${i===7?'A':i+1}</span><select data-cd-mode="${k}" aria-label="${k}冷却模式"><option value="unlimited" ${cd[k].mode==='unlimited'?'selected':''}>无限生成</option><option value="configured" ${cd[k].mode==='configured'?'selected':''}>预设CD</option></select><input type="number" min="1" max="10000" value="${cd[k].batch}" data-cd-batch="${k}" aria-label="${k}每轮点击"><input type="number" min="0" max="86400" value="${cd[k].seconds}" data-cd-seconds="${k}" aria-label="${k}冷却秒数"></div>`).join('')}</div><button id="save-cd" class="primary full">保存预留设置</button>`;$('#save-cd').onclick=()=>{try{OS.forEach(k=>{cd[k]={mode:document.querySelector(`[data-cd-mode="${k}"]`).value,batch:Number(document.querySelector(`[data-cd-batch="${k}"]`).value),seconds:Number(document.querySelector(`[data-cd-seconds="${k}"]`).value)}});validateScenario({...settings,cd},state.day);savePatch({cd});$('#detail').close();context.paint();toast('CD设置已保存；当前模拟暂不执行等待')}catch(e){toast(e.message)}};if(!$('#detail').open)$('#detail').showModal()}
export function cdTimeLabel(){return Object.values(loadScenario().cd).some(c=>c.mode==='configured')?'未计算（已预设）':'0秒（无限生成）'}
